"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-04 22:10:12.948637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('ats', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('curated', 'discovered')", name='ck_organizations_origin'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('manual', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id')
    )
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ats_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('workplace_type', sa.Text(), nullable=True),
    sa.Column('team', sa.Text(), nullable=True),
    sa.Column('commitment', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('new', 'reviewed', 'applied', 'rejected', 'likely_closed')", name='ck_postings_status'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'ats_id', name='uq_postings_source_ats_id')
    )
    op.create_index(op.f('ix_postings_org'), 'postings', ['org'], unique=False)
    op.create_index('ix_postings_org_status', 'postings', ['org', 'status'], unique=False)
    op.create_index(op.f('ix_postings_status'), 'postings', ['status'], unique=False)
    op.create_index(op.f('ix_postings_tier'), 'postings', ['tier'], unique=False)
    op.create_index(op.f('ix_postings_workplace_type'), 'postings', ['workplace_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postings_workplace_type'), table_name='postings')
    op.drop_index(op.f('ix_postings_tier'), table_name='postings')
    op.drop_index(op.f('ix_postings_status'), table_name='postings')
    op.drop_index('ix_postings_org_status', table_name='postings')
    op.drop_index(op.f('ix_postings_org'), table_name='postings')
    op.drop_table('postings')
    op.drop_table('searches')
    op.drop_table('organizations')
    # ### end Alembic commands ###
